stages:
  - build
  - test

cmake:gnu:
  stage: build
  image: debian:stable
  script:
    # All of this should be in a separate image
    - apt update
    - apt install build-essential mpich python3-dev cmake python3-numpy libsqlite3-dev python3-torch python3-sklearn -y
    # And now we actually build
    - mkdir bld && cd bld
    - cmake ../GLUECode_Library
    - make
  artifacts:
    paths:
    - bld
    expire_in: 1 day

test:gnu:
  stage: test
  image: debian:stable
  script:
    # All of this should be in a separate image
    - apt update
    - apt install build-essential mpich python3-dev cmake python3-numpy libsqlite3-dev python3-torch python3-sklearn -y
    # And now we actually test
    - mkdir serial && cd serial
    - bash ../examples/sniffTest_serial.sh ../bld/tests/sniffTest_mpi
  needs: ["cmake:gnu"]
  dependencies:
    - cmake:gnu

test:gnu_mpi:
  stage: test
  image: debian:stable
  script:
    # All of this should be in a separate image
    - apt update
    - apt install build-essential mpich python3-dev cmake python3-numpy libsqlite3-dev python3-torch python3-sklearn -y
    # And now we actually test
    - mkdir mpi && cd mpi
    - bash ../examples/sniffTest_mpi.sh ../bld/tests/sniffTest_mpi
  needs: ["cmake:gnu"]
  dependencies:
    - cmake:gnu

